#############################################################################
# Makefile for building: beagletomb
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Fri Mar 16 12:04:18 2012
# Project:  beagletomb.pro
# Template: app
# Command: $(QMAKE) -o Makefile beagletomb.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = src/beaglemain.h \
		src/sync.h \
		src/songObj.h \
		src/readDB.h \
		src/qmpyuvreader.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/prefdialog.h \
		src/mysqlconn.h \
		src/mplaycon.h \
		src/about.h \
		src/newplaylist.h \
		src/playlistobj.h \
		src/sync.h \
		src/songObj.h \
		src/readDB.h \
		src/qmpyuvreader.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/prefdialog.h \
		src/playlistobj.h \
		src/newplaylist.h \
		src/mysqlconn.h \
		src/mplaycon.h \
		src/beaglemain.h \
		src/about.h \
		src/openplaylist.h \
		src/radioObj.h
SOURCES = src/main.cpp \
		src/beaglemain.cpp \
		src/sync.cpp \
		src/songObj.cpp \
		src/readDB.cpp \
		src/qmpwidget.cpp \
		src/preferences.cpp \
		src/prefdialog.cpp \
		src/mysqlconn.cpp \
		src/mplaycon.cpp \
		src/about.cpp \
		src/newplaylist.cpp \
		src/playlistobj.cpp \
		src/openplaylist.cpp \
		src/radioObj.cpp
OBJECTS = main.o \
		beaglemain.o \
		sync.o \
		songObj.o \
		readDB.o \
		qmpwidget.o \
		preferences.o \
		prefdialog.o \
		mysqlconn.o \
		mplaycon.o \
		about.o \
		newplaylist.o \
		playlistobj.o \
		openplaylist.o \
		radioObj.o \
		prefdialog.o \
		about.o \
		newplaylist.o \
		beaglemain.o \
		openplaylist.o
FORMS = src/prefdialog.ui \
		src/about.ui \
		src/newplaylist.ui \
		src/beaglemain.ui \
		src/openplaylist.ui
UICDECLS = src/prefdialog.h \
		src/about.h \
		src/newplaylist.h \
		src/beaglemain.h \
		src/openplaylist.h
UICIMPLS = src/prefdialog.cpp \
		src/about.cpp \
		src/newplaylist.cpp \
		src/beaglemain.cpp \
		src/openplaylist.cpp
SRCMOC   = src/moc_beaglemain.cpp \
		src/moc_qmpyuvreader.cpp \
		src/moc_qmpwidget.cpp \
		src/moc_prefdialog.cpp \
		src/moc_about.cpp \
		src/moc_newplaylist.cpp \
		src/moc_openplaylist.cpp \
		src/moc_prefdialog.cpp \
		src/moc_about.cpp \
		src/moc_newplaylist.cpp \
		src/moc_beaglemain.cpp \
		src/moc_openplaylist.cpp \
		src/qmpwidget.moc
OBJMOC = moc_beaglemain.o \
		moc_qmpyuvreader.o \
		moc_qmpwidget.o \
		moc_prefdialog.o \
		moc_about.o \
		moc_newplaylist.o \
		moc_openplaylist.o \
		moc_prefdialog.o \
		moc_about.o \
		moc_newplaylist.o \
		moc_beaglemain.o \
		moc_openplaylist.o
DIST	   = beagletomb.pro
QMAKE_TARGET = beagletomb
DESTDIR  = 
TARGET   = beagletomb

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: beagletomb.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile beagletomb.pro
qmake: 
	@$(QMAKE) -o Makefile beagletomb.pro

dist: 
	@mkdir -p .tmp/beagletomb && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/beagletomb/ && ( cd `dirname .tmp/beagletomb` && $(TAR) beagletomb.tar beagletomb && $(GZIP) beagletomb.tar ) && $(MOVE) `dirname .tmp/beagletomb`/beagletomb.tar.gz . && $(DEL_FILE) -r .tmp/beagletomb

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: src/main.cpp src/beaglemain.h \
		src/sync.h \
		src/songObj.h \
		src/readDB.h \
		src/mplaycon.h \
		src/prefdialog.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/about.h \
		src/playlistobj.h \
		src/newplaylist.h \
		src/openplaylist.h \
		src/radioObj.h \
		src/mysqlconn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

beaglemain.o: src/beaglemain.cpp src/beaglemain.h \
		src/sync.h \
		src/songObj.h \
		src/readDB.h \
		src/mplaycon.h \
		src/prefdialog.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/about.h \
		src/playlistobj.h \
		src/newplaylist.h \
		src/openplaylist.h \
		src/radioObj.h \
		src/mysqlconn.h \
		src/beaglemain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o beaglemain.o src/beaglemain.cpp

sync.o: src/sync.cpp src/sync.h \
		src/mysqlconn.h \
		src/readDB.h \
		src/songObj.h \
		src/radioObj.h \
		src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sync.o src/sync.cpp

songObj.o: src/songObj.cpp src/songObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o songObj.o src/songObj.cpp

readDB.o: src/readDB.cpp src/readDB.h \
		src/songObj.h \
		src/radioObj.h \
		src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readDB.o src/readDB.cpp

qmpwidget.o: src/qmpwidget.cpp src/qmpwidget.h \
		src/qmpyuvreader.h \
		src/qmpwidget.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmpwidget.o src/qmpwidget.cpp

preferences.o: src/preferences.cpp src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o src/preferences.cpp

prefdialog.o: src/prefdialog.cpp src/prefdialog.h \
		src/preferences.h \
		src/prefdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prefdialog.o src/prefdialog.cpp

mysqlconn.o: src/mysqlconn.cpp src/mysqlconn.h \
		src/songObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlconn.o src/mysqlconn.cpp

mplaycon.o: src/mplaycon.cpp src/mplaycon.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/playlistobj.h \
		src/songObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mplaycon.o src/mplaycon.cpp

about.o: src/about.cpp src/about.h \
		src/about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o src/about.cpp

newplaylist.o: src/newplaylist.cpp src/newplaylist.h \
		src/ui_newplaylist.h \
		src/preferences.h \
		src/newplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newplaylist.o src/newplaylist.cpp

playlistobj.o: src/playlistobj.cpp src/playlistobj.h \
		src/songObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playlistobj.o src/playlistobj.cpp

openplaylist.o: src/openplaylist.cpp src/openplaylist.h \
		src/preferences.h \
		src/openplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openplaylist.o src/openplaylist.cpp

radioObj.o: src/radioObj.cpp src/radioObj.h \
		src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radioObj.o src/radioObj.cpp

src/prefdialog.h: src/prefdialog.ui 
	$(UIC) src/prefdialog.ui -o src/prefdialog.h

src/prefdialog.cpp: src/prefdialog.h src/prefdialog.ui 
	$(UIC) src/prefdialog.ui -i prefdialog.h -o src/prefdialog.cpp

src/about.h: src/about.ui 
	$(UIC) src/about.ui -o src/about.h

src/about.cpp: src/about.h src/about.ui 
	$(UIC) src/about.ui -i about.h -o src/about.cpp

src/newplaylist.h: src/newplaylist.ui 
	$(UIC) src/newplaylist.ui -o src/newplaylist.h

src/newplaylist.cpp: src/newplaylist.h src/newplaylist.ui 
	$(UIC) src/newplaylist.ui -i newplaylist.h -o src/newplaylist.cpp

src/beaglemain.h: src/beaglemain.ui 
	$(UIC) src/beaglemain.ui -o src/beaglemain.h

src/beaglemain.cpp: src/beaglemain.h src/beaglemain.ui 
	$(UIC) src/beaglemain.ui -i beaglemain.h -o src/beaglemain.cpp

src/openplaylist.h: src/openplaylist.ui 
	$(UIC) src/openplaylist.ui -o src/openplaylist.h

src/openplaylist.cpp: src/openplaylist.h src/openplaylist.ui 
	$(UIC) src/openplaylist.ui -i openplaylist.h -o src/openplaylist.cpp

prefdialog.o: src/prefdialog.cpp src/prefdialog.h \
		src/preferences.h \
		src/prefdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prefdialog.o src/prefdialog.cpp

about.o: src/about.cpp src/about.h \
		src/about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o src/about.cpp

newplaylist.o: src/newplaylist.cpp src/newplaylist.h \
		src/ui_newplaylist.h \
		src/preferences.h \
		src/newplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newplaylist.o src/newplaylist.cpp

beaglemain.o: src/beaglemain.cpp src/beaglemain.h \
		src/sync.h \
		src/songObj.h \
		src/readDB.h \
		src/mplaycon.h \
		src/prefdialog.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/about.h \
		src/playlistobj.h \
		src/newplaylist.h \
		src/openplaylist.h \
		src/radioObj.h \
		src/mysqlconn.h \
		src/beaglemain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o beaglemain.o src/beaglemain.cpp

openplaylist.o: src/openplaylist.cpp src/openplaylist.h \
		src/preferences.h \
		src/openplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openplaylist.o src/openplaylist.cpp

moc_beaglemain.o: src/moc_beaglemain.cpp  src/beaglemain.h src/sync.h \
		src/songObj.h \
		src/readDB.h \
		src/mplaycon.h \
		src/prefdialog.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/about.h \
		src/playlistobj.h \
		src/newplaylist.h \
		src/openplaylist.h \
		src/radioObj.h \
		src/mysqlconn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_beaglemain.o src/moc_beaglemain.cpp

moc_qmpyuvreader.o: src/moc_qmpyuvreader.cpp  src/qmpyuvreader.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmpyuvreader.o src/moc_qmpyuvreader.cpp

moc_qmpwidget.o: src/moc_qmpwidget.cpp  src/qmpwidget.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmpwidget.o src/moc_qmpwidget.cpp

moc_prefdialog.o: src/moc_prefdialog.cpp  src/prefdialog.h src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prefdialog.o src/moc_prefdialog.cpp

moc_about.o: src/moc_about.cpp  src/about.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o src/moc_about.cpp

moc_newplaylist.o: src/moc_newplaylist.cpp  src/newplaylist.h src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newplaylist.o src/moc_newplaylist.cpp

moc_openplaylist.o: src/moc_openplaylist.cpp  src/openplaylist.h src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openplaylist.o src/moc_openplaylist.cpp

moc_prefdialog.o: src/moc_prefdialog.cpp  src/prefdialog.h src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prefdialog.o src/moc_prefdialog.cpp

moc_about.o: src/moc_about.cpp  src/about.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o src/moc_about.cpp

moc_newplaylist.o: src/moc_newplaylist.cpp  src/newplaylist.h src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newplaylist.o src/moc_newplaylist.cpp

moc_beaglemain.o: src/moc_beaglemain.cpp  src/beaglemain.h src/sync.h \
		src/songObj.h \
		src/readDB.h \
		src/mplaycon.h \
		src/prefdialog.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/about.h \
		src/playlistobj.h \
		src/newplaylist.h \
		src/openplaylist.h \
		src/radioObj.h \
		src/mysqlconn.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_beaglemain.o src/moc_beaglemain.cpp

moc_openplaylist.o: src/moc_openplaylist.cpp  src/openplaylist.h src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openplaylist.o src/moc_openplaylist.cpp

src/moc_beaglemain.cpp: $(MOC) src/beaglemain.h
	$(MOC) src/beaglemain.h -o src/moc_beaglemain.cpp

src/moc_qmpyuvreader.cpp: $(MOC) src/qmpyuvreader.h
	$(MOC) src/qmpyuvreader.h -o src/moc_qmpyuvreader.cpp

src/moc_qmpwidget.cpp: $(MOC) src/qmpwidget.h
	$(MOC) src/qmpwidget.h -o src/moc_qmpwidget.cpp

src/moc_prefdialog.cpp: $(MOC) src/prefdialog.h
	$(MOC) src/prefdialog.h -o src/moc_prefdialog.cpp

src/moc_about.cpp: $(MOC) src/about.h
	$(MOC) src/about.h -o src/moc_about.cpp

src/moc_newplaylist.cpp: $(MOC) src/newplaylist.h
	$(MOC) src/newplaylist.h -o src/moc_newplaylist.cpp

src/moc_qmpyuvreader.cpp: $(MOC) src/qmpyuvreader.h
	$(MOC) src/qmpyuvreader.h -o src/moc_qmpyuvreader.cpp

src/moc_qmpwidget.cpp: $(MOC) src/qmpwidget.h
	$(MOC) src/qmpwidget.h -o src/moc_qmpwidget.cpp

src/moc_prefdialog.cpp: $(MOC) src/prefdialog.h
	$(MOC) src/prefdialog.h -o src/moc_prefdialog.cpp

src/moc_newplaylist.cpp: $(MOC) src/newplaylist.h
	$(MOC) src/newplaylist.h -o src/moc_newplaylist.cpp

src/moc_beaglemain.cpp: $(MOC) src/beaglemain.h
	$(MOC) src/beaglemain.h -o src/moc_beaglemain.cpp

src/moc_about.cpp: $(MOC) src/about.h
	$(MOC) src/about.h -o src/moc_about.cpp

src/moc_openplaylist.cpp: $(MOC) src/openplaylist.h
	$(MOC) src/openplaylist.h -o src/moc_openplaylist.cpp

src/qmpwidget.moc: $(MOC) src/qmpwidget.cpp
	$(MOC) src/qmpwidget.cpp -o src/qmpwidget.moc

src/moc_prefdialog.cpp: $(MOC) src/prefdialog.h
	$(MOC) src/prefdialog.h -o src/moc_prefdialog.cpp

src/moc_about.cpp: $(MOC) src/about.h
	$(MOC) src/about.h -o src/moc_about.cpp

src/moc_newplaylist.cpp: $(MOC) src/newplaylist.h
	$(MOC) src/newplaylist.h -o src/moc_newplaylist.cpp

src/moc_beaglemain.cpp: $(MOC) src/beaglemain.h
	$(MOC) src/beaglemain.h -o src/moc_beaglemain.cpp

src/moc_openplaylist.cpp: $(MOC) src/openplaylist.h
	$(MOC) src/openplaylist.h -o src/moc_openplaylist.cpp

####### Install

install:  

uninstall:  

