#############################################################################
# Makefile for building: beagletomb
# Generated by qmake (2.01a) (Qt 4.7.2) on: Sat Apr 14 20:42:07 2012
# Project:  beagletomb.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile beagletomb.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lQtSql -lQtOpenGL -lQtGui -lQtNetwork -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/beaglemain.cpp \
		src/sync.cpp \
		src/readDB.cpp \
		src/qmpwidget.cpp \
		src/preferences.cpp \
		src/prefdialog.cpp \
		src/mysqlconn.cpp \
		src/mplaycon.cpp \
		src/about.cpp \
		src/playlistobj.cpp \
		src/radioObj.cpp \
		src/fileobj.cpp \
		src/localsync.cpp \
		src/newplaylist.cpp moc_beaglemain.cpp \
		moc_qmpyuvreader.cpp \
		moc_qmpwidget.cpp \
		moc_prefdialog.cpp \
		moc_about.cpp \
		moc_newplaylist.cpp \
		qrc_BTres.cpp
OBJECTS       = main.o \
		beaglemain.o \
		sync.o \
		readDB.o \
		qmpwidget.o \
		preferences.o \
		prefdialog.o \
		mysqlconn.o \
		mplaycon.o \
		about.o \
		playlistobj.o \
		radioObj.o \
		fileobj.o \
		localsync.o \
		newplaylist.o \
		moc_beaglemain.o \
		moc_qmpyuvreader.o \
		moc_qmpwidget.o \
		moc_prefdialog.o \
		moc_about.o \
		moc_newplaylist.o \
		qrc_BTres.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		beagletomb.pro
QMAKE_TARGET  = beagletomb
DESTDIR       = 
TARGET        = beagletomb

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_prefdialog.h ui_about.h ui_beaglemain.h ui_newplaylist.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: beagletomb.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile beagletomb.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile beagletomb.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/beagletomb1.0.0 || $(MKDIR) .tmp/beagletomb1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/beagletomb1.0.0/ && $(COPY_FILE) --parents src/beaglemain.h src/sync.h src/readDB.h src/qmpyuvreader.h src/qmpwidget.h src/preferences.h src/prefdialog.h src/mysqlconn.h src/mplaycon.h src/about.h src/playlistobj.h src/sync.h src/readDB.h src/qmpyuvreader.h src/qmpwidget.h src/preferences.h src/prefdialog.h src/playlistobj.h src/mysqlconn.h src/mplaycon.h src/beaglemain.h src/about.h src/radioObj.h src/fileobj.h src/localsync.h src/newplaylist.h .tmp/beagletomb1.0.0/ && $(COPY_FILE) --parents images/BTres.qrc .tmp/beagletomb1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/beaglemain.cpp src/sync.cpp src/readDB.cpp src/qmpwidget.cpp src/preferences.cpp src/prefdialog.cpp src/mysqlconn.cpp src/mplaycon.cpp src/about.cpp src/playlistobj.cpp src/radioObj.cpp src/fileobj.cpp src/localsync.cpp src/newplaylist.cpp .tmp/beagletomb1.0.0/ && $(COPY_FILE) --parents src/prefdialog.ui src/about.ui src/beaglemain.ui src/newplaylist.ui .tmp/beagletomb1.0.0/ && (cd `dirname .tmp/beagletomb1.0.0` && $(TAR) beagletomb1.0.0.tar beagletomb1.0.0 && $(COMPRESS) beagletomb1.0.0.tar) && $(MOVE) `dirname .tmp/beagletomb1.0.0`/beagletomb1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/beagletomb1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_beaglemain.cpp moc_qmpyuvreader.cpp moc_qmpwidget.cpp moc_prefdialog.cpp moc_about.cpp moc_qmpyuvreader.cpp moc_qmpwidget.cpp moc_prefdialog.cpp moc_beaglemain.cpp moc_about.cpp moc_newplaylist.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_beaglemain.cpp moc_qmpyuvreader.cpp moc_qmpwidget.cpp moc_prefdialog.cpp moc_about.cpp moc_qmpyuvreader.cpp moc_qmpwidget.cpp moc_prefdialog.cpp moc_beaglemain.cpp moc_about.cpp moc_newplaylist.cpp
moc_beaglemain.cpp: src/sync.h \
		src/mysqlconn.h \
		src/fileobj.h \
		src/preferences.h \
		src/readDB.h \
		src/radioObj.h \
		src/mplaycon.h \
		src/qmpwidget.h \
		src/playlistobj.h \
		src/prefdialog.h \
		src/about.h \
		src/localsync.h \
		src/newplaylist.h \
		src/beaglemain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/beaglemain.h -o moc_beaglemain.cpp

moc_qmpyuvreader.cpp: src/qmpyuvreader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpyuvreader.h -o moc_qmpyuvreader.cpp

moc_qmpwidget.cpp: src/qmpwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpwidget.h -o moc_qmpwidget.cpp

moc_prefdialog.cpp: src/preferences.h \
		src/prefdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/prefdialog.h -o moc_prefdialog.cpp

moc_about.cpp: src/about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/about.h -o moc_about.cpp

moc_qmpyuvreader.cpp: src/qmpyuvreader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpyuvreader.h -o moc_qmpyuvreader.cpp

moc_qmpwidget.cpp: src/qmpwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpwidget.h -o moc_qmpwidget.cpp

moc_prefdialog.cpp: src/preferences.h \
		src/prefdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/prefdialog.h -o moc_prefdialog.cpp

moc_beaglemain.cpp: src/sync.h \
		src/mysqlconn.h \
		src/fileobj.h \
		src/preferences.h \
		src/readDB.h \
		src/radioObj.h \
		src/mplaycon.h \
		src/qmpwidget.h \
		src/playlistobj.h \
		src/prefdialog.h \
		src/about.h \
		src/localsync.h \
		src/newplaylist.h \
		src/beaglemain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/beaglemain.h -o moc_beaglemain.cpp

moc_about.cpp: src/about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/about.h -o moc_about.cpp

moc_newplaylist.cpp: src/newplaylist.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/newplaylist.h -o moc_newplaylist.cpp

compiler_rcc_make_all: qrc_BTres.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_BTres.cpp
qrc_BTres.cpp: images/BTres.qrc \
		images/RWD_icon.png \
		images/DOWN_icon.png \
		images/PAUSE_icon.png \
		images/RRWD_icon.png \
		images/FFWD_icon.png \
		images/beagletomb_icon.png \
		images/RPT_icon.png \
		images/STOP_icon.png \
		images/FWD_icon.png \
		images/UP_icon.png
	/usr/bin/rcc -name BTres images/BTres.qrc -o qrc_BTres.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: qmpwidget.moc
compiler_moc_source_clean:
	-$(DEL_FILE) qmpwidget.moc
qmpwidget.moc: src/qmpwidget.h \
		src/qmpyuvreader.h \
		src/qmpwidget.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/qmpwidget.cpp -o qmpwidget.moc

compiler_uic_make_all: ui_prefdialog.h ui_about.h ui_beaglemain.h ui_newplaylist.h
compiler_uic_clean:
	-$(DEL_FILE) ui_prefdialog.h ui_about.h ui_beaglemain.h ui_newplaylist.h
ui_prefdialog.h: src/prefdialog.ui
	/usr/bin/uic-qt4 src/prefdialog.ui -o ui_prefdialog.h

ui_about.h: src/about.ui
	/usr/bin/uic-qt4 src/about.ui -o ui_about.h

ui_beaglemain.h: src/beaglemain.ui
	/usr/bin/uic-qt4 src/beaglemain.ui -o ui_beaglemain.h

ui_newplaylist.h: src/newplaylist.ui
	/usr/bin/uic-qt4 src/newplaylist.ui -o ui_newplaylist.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/beaglemain.h \
		src/sync.h \
		src/mysqlconn.h \
		src/fileobj.h \
		src/preferences.h \
		src/readDB.h \
		src/radioObj.h \
		src/mplaycon.h \
		src/qmpwidget.h \
		src/playlistobj.h \
		src/prefdialog.h \
		src/about.h \
		src/localsync.h \
		src/newplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

beaglemain.o: src/beaglemain.cpp src/beaglemain.h \
		src/sync.h \
		src/mysqlconn.h \
		src/fileobj.h \
		src/preferences.h \
		src/readDB.h \
		src/radioObj.h \
		src/mplaycon.h \
		src/qmpwidget.h \
		src/playlistobj.h \
		src/prefdialog.h \
		src/about.h \
		src/localsync.h \
		src/newplaylist.h \
		ui_beaglemain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o beaglemain.o src/beaglemain.cpp

sync.o: src/sync.cpp src/sync.h \
		src/mysqlconn.h \
		src/fileobj.h \
		src/preferences.h \
		src/readDB.h \
		src/radioObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sync.o src/sync.cpp

readDB.o: src/readDB.cpp src/readDB.h \
		src/radioObj.h \
		src/preferences.h \
		src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readDB.o src/readDB.cpp

qmpwidget.o: src/qmpwidget.cpp src/qmpwidget.h \
		src/qmpyuvreader.h \
		qmpwidget.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmpwidget.o src/qmpwidget.cpp

preferences.o: src/preferences.cpp src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o src/preferences.cpp

prefdialog.o: src/prefdialog.cpp src/prefdialog.h \
		src/preferences.h \
		ui_prefdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prefdialog.o src/prefdialog.cpp

mysqlconn.o: src/mysqlconn.cpp src/mysqlconn.h \
		src/fileobj.h \
		src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlconn.o src/mysqlconn.cpp

mplaycon.o: src/mplaycon.cpp src/mplaycon.h \
		src/qmpwidget.h \
		src/preferences.h \
		src/playlistobj.h \
		src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mplaycon.o src/mplaycon.cpp

about.o: src/about.cpp src/about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o src/about.cpp

playlistobj.o: src/playlistobj.cpp src/playlistobj.h \
		src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playlistobj.o src/playlistobj.cpp

radioObj.o: src/radioObj.cpp src/radioObj.h \
		src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radioObj.o src/radioObj.cpp

fileobj.o: src/fileobj.cpp src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileobj.o src/fileobj.cpp

localsync.o: src/localsync.cpp src/localsync.h \
		src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localsync.o src/localsync.cpp

newplaylist.o: src/newplaylist.cpp src/newplaylist.h \
		ui_newplaylist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newplaylist.o src/newplaylist.cpp

moc_beaglemain.o: moc_beaglemain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_beaglemain.o moc_beaglemain.cpp

moc_qmpyuvreader.o: moc_qmpyuvreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmpyuvreader.o moc_qmpyuvreader.cpp

moc_qmpwidget.o: moc_qmpwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmpwidget.o moc_qmpwidget.cpp

moc_prefdialog.o: moc_prefdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prefdialog.o moc_prefdialog.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

moc_newplaylist.o: moc_newplaylist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newplaylist.o moc_newplaylist.cpp

qrc_BTres.o: qrc_BTres.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_BTres.o qrc_BTres.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/ || $(MKDIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/ || $(MKDIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/ 
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/about.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/about.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/about.ui $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/beaglemain.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/beaglemain.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/beaglemain.ui $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/fileobj.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/fileobj.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/localsync.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/localsync.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/main.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/mplaycon.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/mplaycon.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/mysqlconn.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/mysqlconn.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/newplaylist.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/newplaylist.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/newplaylist.ui $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/playlistobj.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/playlistobj.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/prefdialog.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/prefdialog.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/prefdialog.ui $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/preferences.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/preferences.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/qmpwidget.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/qmpwidget.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/qmpwidget.pri $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/qmpyuvreader.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/radioObj.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/radioObj.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/readDB.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/readDB.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/src.pro $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/sync.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/src/sync.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/about.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/about.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/about.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/beaglemain.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/beaglemain.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/beaglemain.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/fileobj.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/fileobj.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/localsync.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/localsync.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/mplaycon.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/mplaycon.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/mysqlconn.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/mysqlconn.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/newplaylist.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/newplaylist.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/newplaylist.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/playlistobj.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/playlistobj.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/prefdialog.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/prefdialog.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/prefdialog.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/preferences.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/preferences.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/qmpwidget.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/qmpwidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/qmpwidget.pri 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/qmpyuvreader.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/radioObj.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/radioObj.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/readDB.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/readDB.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/src.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/sync.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/sync.h
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/ 


install_documentation: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/ || $(MKDIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/ 
	-$(INSTALL_PROGRAM) /home/skynet/Desktop/beagletomb/docs/compile.sh $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-strip $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/compile.sh
	-$(INSTALL_PROGRAM) /home/skynet/Desktop/beagletomb/docs/configure.sh $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-strip $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/configure.sh
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/docs/HostSetupREAD $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_PROGRAM) /home/skynet/Desktop/beagletomb/docs/install.sh $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-strip $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/install.sh
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/docs/instprint.sh $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/docs/instructions $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/docs/README.txt $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/docs/readme_install.txt $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/


uninstall_documentation:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/compile.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/configure.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/HostSetupREAD 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/install.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/instprint.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/instructions 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/README.txt 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/readme_install.txt
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/ 


install_other: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ || $(MKDIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ 
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/about.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/beaglemain.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/beagletomb.desktop $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/beagletomb.pro $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/beagletomb.pro.user $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/changelog $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/copyright $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_DIR) /home/skynet/Desktop/beagletomb/debian $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_DIR) /home/skynet/Desktop/beagletomb/docs $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/fileobj.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_DIR) /home/skynet/Desktop/beagletomb/images $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/localsync.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/main.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/Makefile $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/mplaycon.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/mysqlconn.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/playlistobj.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/prefdialog.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/preferences.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/qmpwidget.moc $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/qmpwidget.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/radioObj.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/readDB.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/readme.txt $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_DIR) /home/skynet/Desktop/beagletomb/src $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/sync.o $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/ui_about.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/ui_beaglemain.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/ui_newplaylist.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/Desktop/beagletomb/ui_prefdialog.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/


uninstall_other:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/about.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/beaglemain.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/beagletomb.desktop 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/beagletomb.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/beagletomb.pro.user 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/changelog 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/copyright 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/debian 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/docs 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/fileobj.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/images 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/localsync.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/main.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/Makefile 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/mplaycon.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/mysqlconn.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/playlistobj.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/prefdialog.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/preferences.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/qmpwidget.moc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/qmpwidget.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/radioObj.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/readDB.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/readme.txt 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/src 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/sync.o 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ui_about.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ui_beaglemain.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ui_newplaylist.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ui_prefdialog.h
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ 


install:  install_target install_sources install_documentation install_other  FORCE

uninstall: uninstall_target uninstall_sources uninstall_documentation uninstall_other   FORCE

FORCE:

