#############################################################################
# Makefile for building: beagletomb
# Generated by qmake (2.01a) (Qt 4.7.2) on: Tue Apr 10 17:26:57 2012
# Project:  ../beagletomb/beagletomb.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile ../beagletomb/beagletomb.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I../beagletomb -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/X11R6/include -I. -I. -I../beagletomb -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lQtSql -lQtOpenGL -lQtGui -lQtNetwork -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../beagletomb/src/main.cpp \
		../beagletomb/src/beaglemain.cpp \
		../beagletomb/src/sync.cpp \
		../beagletomb/src/readDB.cpp \
		../beagletomb/src/qmpwidget.cpp \
		../beagletomb/src/preferences.cpp \
		../beagletomb/src/prefdialog.cpp \
		../beagletomb/src/mysqlconn.cpp \
		../beagletomb/src/mplaycon.cpp \
		../beagletomb/src/about.cpp \
		../beagletomb/src/playlistobj.cpp \
		../beagletomb/src/radioObj.cpp \
		../beagletomb/src/fileobj.cpp \
		../beagletomb/src/localsync.cpp moc_beaglemain.cpp \
		moc_qmpyuvreader.cpp \
		moc_qmpwidget.cpp \
		moc_prefdialog.cpp \
		moc_about.cpp \
		qrc_BTres.cpp
OBJECTS       = main.o \
		beaglemain.o \
		sync.o \
		readDB.o \
		qmpwidget.o \
		preferences.o \
		prefdialog.o \
		mysqlconn.o \
		mplaycon.o \
		about.o \
		playlistobj.o \
		radioObj.o \
		fileobj.o \
		localsync.o \
		moc_beaglemain.o \
		moc_qmpyuvreader.o \
		moc_qmpwidget.o \
		moc_prefdialog.o \
		moc_about.o \
		qrc_BTres.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../beagletomb/beagletomb.pro
QMAKE_TARGET  = beagletomb
DESTDIR       = 
TARGET        = beagletomb

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_prefdialog.h ui_about.h ui_beaglemain.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../beagletomb/beagletomb.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile ../beagletomb/beagletomb.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile ../beagletomb/beagletomb.pro

dist: 
	@$(CHK_DIR_EXISTS) ../beagletomb/.tmp/beagletomb1.0.0 || $(MKDIR) ../beagletomb/.tmp/beagletomb1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../beagletomb/.tmp/beagletomb1.0.0/ && $(COPY_FILE) --parents ../beagletomb/src/beaglemain.h ../beagletomb/src/sync.h ../beagletomb/src/readDB.h ../beagletomb/src/qmpyuvreader.h ../beagletomb/src/qmpwidget.h ../beagletomb/src/preferences.h ../beagletomb/src/prefdialog.h ../beagletomb/src/mysqlconn.h ../beagletomb/src/mplaycon.h ../beagletomb/src/about.h ../beagletomb/src/playlistobj.h ../beagletomb/src/sync.h ../beagletomb/src/readDB.h ../beagletomb/src/qmpyuvreader.h ../beagletomb/src/qmpwidget.h ../beagletomb/src/preferences.h ../beagletomb/src/prefdialog.h ../beagletomb/src/playlistobj.h ../beagletomb/src/mysqlconn.h ../beagletomb/src/mplaycon.h ../beagletomb/src/beaglemain.h ../beagletomb/src/about.h ../beagletomb/src/radioObj.h ../beagletomb/src/fileobj.h ../beagletomb/src/localsync.h ../beagletomb/.tmp/beagletomb1.0.0/ && $(COPY_FILE) --parents ../beagletomb/images/BTres.qrc ../beagletomb/.tmp/beagletomb1.0.0/ && $(COPY_FILE) --parents ../beagletomb/src/main.cpp ../beagletomb/src/beaglemain.cpp ../beagletomb/src/sync.cpp ../beagletomb/src/readDB.cpp ../beagletomb/src/qmpwidget.cpp ../beagletomb/src/preferences.cpp ../beagletomb/src/prefdialog.cpp ../beagletomb/src/mysqlconn.cpp ../beagletomb/src/mplaycon.cpp ../beagletomb/src/about.cpp ../beagletomb/src/playlistobj.cpp ../beagletomb/src/radioObj.cpp ../beagletomb/src/fileobj.cpp ../beagletomb/src/localsync.cpp ../beagletomb/.tmp/beagletomb1.0.0/ && $(COPY_FILE) --parents ../beagletomb/src/prefdialog.ui ../beagletomb/src/about.ui ../beagletomb/src/beaglemain.ui ../beagletomb/.tmp/beagletomb1.0.0/ && (cd `dirname ../beagletomb/.tmp/beagletomb1.0.0` && $(TAR) beagletomb1.0.0.tar beagletomb1.0.0 && $(COMPRESS) beagletomb1.0.0.tar) && $(MOVE) `dirname ../beagletomb/.tmp/beagletomb1.0.0`/beagletomb1.0.0.tar.gz . && $(DEL_FILE) -r ../beagletomb/.tmp/beagletomb1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_beaglemain.cpp moc_qmpyuvreader.cpp moc_qmpwidget.cpp moc_prefdialog.cpp moc_about.cpp moc_qmpyuvreader.cpp moc_qmpwidget.cpp moc_prefdialog.cpp moc_beaglemain.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_beaglemain.cpp moc_qmpyuvreader.cpp moc_qmpwidget.cpp moc_prefdialog.cpp moc_about.cpp moc_qmpyuvreader.cpp moc_qmpwidget.cpp moc_prefdialog.cpp moc_beaglemain.cpp moc_about.cpp
moc_beaglemain.cpp: ../beagletomb/src/sync.h \
		../beagletomb/src/mysqlconn.h \
		../beagletomb/src/fileobj.h \
		../beagletomb/src/readDB.h \
		../beagletomb/src/radioObj.h \
		../beagletomb/src/preferences.h \
		../beagletomb/src/mplaycon.h \
		../beagletomb/src/qmpwidget.h \
		../beagletomb/src/playlistobj.h \
		../beagletomb/src/prefdialog.h \
		../beagletomb/src/about.h \
		../beagletomb/src/localsync.h \
		../beagletomb/src/beaglemain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/beaglemain.h -o moc_beaglemain.cpp

moc_qmpyuvreader.cpp: ../beagletomb/src/qmpyuvreader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/qmpyuvreader.h -o moc_qmpyuvreader.cpp

moc_qmpwidget.cpp: ../beagletomb/src/qmpwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/qmpwidget.h -o moc_qmpwidget.cpp

moc_prefdialog.cpp: ../beagletomb/src/preferences.h \
		../beagletomb/src/prefdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/prefdialog.h -o moc_prefdialog.cpp

moc_about.cpp: ../beagletomb/src/about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/about.h -o moc_about.cpp

moc_qmpyuvreader.cpp: ../beagletomb/src/qmpyuvreader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/qmpyuvreader.h -o moc_qmpyuvreader.cpp

moc_qmpwidget.cpp: ../beagletomb/src/qmpwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/qmpwidget.h -o moc_qmpwidget.cpp

moc_prefdialog.cpp: ../beagletomb/src/preferences.h \
		../beagletomb/src/prefdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/prefdialog.h -o moc_prefdialog.cpp

moc_beaglemain.cpp: ../beagletomb/src/sync.h \
		../beagletomb/src/mysqlconn.h \
		../beagletomb/src/fileobj.h \
		../beagletomb/src/readDB.h \
		../beagletomb/src/radioObj.h \
		../beagletomb/src/preferences.h \
		../beagletomb/src/mplaycon.h \
		../beagletomb/src/qmpwidget.h \
		../beagletomb/src/playlistobj.h \
		../beagletomb/src/prefdialog.h \
		../beagletomb/src/about.h \
		../beagletomb/src/localsync.h \
		../beagletomb/src/beaglemain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/beaglemain.h -o moc_beaglemain.cpp

moc_about.cpp: ../beagletomb/src/about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/about.h -o moc_about.cpp

compiler_rcc_make_all: qrc_BTres.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_BTres.cpp
qrc_BTres.cpp: ../beagletomb/images/BTres.qrc \
		../beagletomb/images/RWD_icon.png \
		../beagletomb/images/DOWN_icon.png \
		../beagletomb/images/PAUSE_icon.png \
		../beagletomb/images/RRWD_icon.png \
		../beagletomb/images/FFWD_icon.png \
		../beagletomb/images/beagletomb_icon.png \
		../beagletomb/images/RPT_icon.png \
		../beagletomb/images/STOP_icon.png \
		../beagletomb/images/FWD_icon.png \
		../beagletomb/images/UP_icon.png
	/usr/bin/rcc -name BTres ../beagletomb/images/BTres.qrc -o qrc_BTres.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: qmpwidget.moc
compiler_moc_source_clean:
	-$(DEL_FILE) qmpwidget.moc
qmpwidget.moc: ../beagletomb/src/qmpwidget.h \
		../beagletomb/src/qmpyuvreader.h \
		../beagletomb/src/qmpwidget.cpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../beagletomb/src/qmpwidget.cpp -o qmpwidget.moc

compiler_uic_make_all: ui_prefdialog.h ui_about.h ui_beaglemain.h
compiler_uic_clean:
	-$(DEL_FILE) ui_prefdialog.h ui_about.h ui_beaglemain.h
ui_prefdialog.h: ../beagletomb/src/prefdialog.ui
	/usr/bin/uic-qt4 ../beagletomb/src/prefdialog.ui -o ui_prefdialog.h

ui_about.h: ../beagletomb/src/about.ui
	/usr/bin/uic-qt4 ../beagletomb/src/about.ui -o ui_about.h

ui_beaglemain.h: ../beagletomb/src/beaglemain.ui
	/usr/bin/uic-qt4 ../beagletomb/src/beaglemain.ui -o ui_beaglemain.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

main.o: ../beagletomb/src/main.cpp ../beagletomb/src/beaglemain.h \
		../beagletomb/src/sync.h \
		../beagletomb/src/mysqlconn.h \
		../beagletomb/src/fileobj.h \
		../beagletomb/src/readDB.h \
		../beagletomb/src/radioObj.h \
		../beagletomb/src/preferences.h \
		../beagletomb/src/mplaycon.h \
		../beagletomb/src/qmpwidget.h \
		../beagletomb/src/playlistobj.h \
		../beagletomb/src/prefdialog.h \
		../beagletomb/src/about.h \
		../beagletomb/src/localsync.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../beagletomb/src/main.cpp

beaglemain.o: ../beagletomb/src/beaglemain.cpp ../beagletomb/src/beaglemain.h \
		../beagletomb/src/sync.h \
		../beagletomb/src/mysqlconn.h \
		../beagletomb/src/fileobj.h \
		../beagletomb/src/readDB.h \
		../beagletomb/src/radioObj.h \
		../beagletomb/src/preferences.h \
		../beagletomb/src/mplaycon.h \
		../beagletomb/src/qmpwidget.h \
		../beagletomb/src/playlistobj.h \
		../beagletomb/src/prefdialog.h \
		../beagletomb/src/about.h \
		../beagletomb/src/localsync.h \
		ui_beaglemain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o beaglemain.o ../beagletomb/src/beaglemain.cpp

sync.o: ../beagletomb/src/sync.cpp ../beagletomb/src/sync.h \
		../beagletomb/src/mysqlconn.h \
		../beagletomb/src/fileobj.h \
		../beagletomb/src/readDB.h \
		../beagletomb/src/radioObj.h \
		../beagletomb/src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sync.o ../beagletomb/src/sync.cpp

readDB.o: ../beagletomb/src/readDB.cpp ../beagletomb/src/readDB.h \
		../beagletomb/src/radioObj.h \
		../beagletomb/src/preferences.h \
		../beagletomb/src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readDB.o ../beagletomb/src/readDB.cpp

qmpwidget.o: ../beagletomb/src/qmpwidget.cpp ../beagletomb/src/qmpwidget.h \
		../beagletomb/src/qmpyuvreader.h \
		qmpwidget.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmpwidget.o ../beagletomb/src/qmpwidget.cpp

preferences.o: ../beagletomb/src/preferences.cpp ../beagletomb/src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o ../beagletomb/src/preferences.cpp

prefdialog.o: ../beagletomb/src/prefdialog.cpp ../beagletomb/src/prefdialog.h \
		../beagletomb/src/preferences.h \
		ui_prefdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prefdialog.o ../beagletomb/src/prefdialog.cpp

mysqlconn.o: ../beagletomb/src/mysqlconn.cpp ../beagletomb/src/mysqlconn.h \
		../beagletomb/src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlconn.o ../beagletomb/src/mysqlconn.cpp

mplaycon.o: ../beagletomb/src/mplaycon.cpp ../beagletomb/src/mplaycon.h \
		../beagletomb/src/qmpwidget.h \
		../beagletomb/src/preferences.h \
		../beagletomb/src/playlistobj.h \
		../beagletomb/src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mplaycon.o ../beagletomb/src/mplaycon.cpp

about.o: ../beagletomb/src/about.cpp ../beagletomb/src/about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o ../beagletomb/src/about.cpp

playlistobj.o: ../beagletomb/src/playlistobj.cpp ../beagletomb/src/playlistobj.h \
		../beagletomb/src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playlistobj.o ../beagletomb/src/playlistobj.cpp

radioObj.o: ../beagletomb/src/radioObj.cpp ../beagletomb/src/radioObj.h \
		../beagletomb/src/preferences.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radioObj.o ../beagletomb/src/radioObj.cpp

fileobj.o: ../beagletomb/src/fileobj.cpp ../beagletomb/src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileobj.o ../beagletomb/src/fileobj.cpp

localsync.o: ../beagletomb/src/localsync.cpp ../beagletomb/src/localsync.h \
		../beagletomb/src/fileobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localsync.o ../beagletomb/src/localsync.cpp

moc_beaglemain.o: moc_beaglemain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_beaglemain.o moc_beaglemain.cpp

moc_qmpyuvreader.o: moc_qmpyuvreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmpyuvreader.o moc_qmpyuvreader.cpp

moc_qmpwidget.o: moc_qmpwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmpwidget.o moc_qmpwidget.cpp

moc_prefdialog.o: moc_prefdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prefdialog.o moc_prefdialog.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

qrc_BTres.o: qrc_BTres.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_BTres.o qrc_BTres.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/ || $(MKDIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/ || $(MKDIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/ 
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/about.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/about.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/about.ui $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/beaglemain.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/beaglemain.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/beaglemain.ui $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/fileobj.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/fileobj.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/localsync.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/localsync.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/main.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/mplaycon.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/mplaycon.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/mysqlconn.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/mysqlconn.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/playlistobj.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/playlistobj.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/prefdialog.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/prefdialog.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/prefdialog.ui $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/preferences.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/preferences.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/qmpwidget.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/qmpwidget.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/qmpwidget.pri $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/qmpyuvreader.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/radioObj.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/radioObj.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/readDB.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/readDB.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/src.pro $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/sync.cpp $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/src/sync.h $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/about.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/about.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/about.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/beaglemain.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/beaglemain.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/beaglemain.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/fileobj.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/fileobj.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/localsync.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/localsync.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/mplaycon.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/mplaycon.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/mysqlconn.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/mysqlconn.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/playlistobj.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/playlistobj.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/prefdialog.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/prefdialog.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/prefdialog.ui 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/preferences.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/preferences.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/qmpwidget.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/qmpwidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/qmpwidget.pri 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/qmpyuvreader.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/radioObj.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/radioObj.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/readDB.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/readDB.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/src.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/sync.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/sync.h
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/src/ 


install_documentation: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/ || $(MKDIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/ 
	-$(INSTALL_PROGRAM) /home/skynet/qt_workspace/beagletomb/docs/compile.sh $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_PROGRAM) /home/skynet/qt_workspace/beagletomb/docs/configure.sh $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/docs/HostSetupREAD $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_PROGRAM) /home/skynet/qt_workspace/beagletomb/docs/install.sh $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/docs/instprint.sh $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/docs/instructions $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/docs/README.txt $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/docs/readme_install.txt $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/


uninstall_documentation:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/compile.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/configure.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/HostSetupREAD 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/install.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/instprint.sh 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/instructions 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/README.txt 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/readme_install.txt
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/docs/ 


install_other: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ || $(MKDIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ 
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/beagletomb.desktop $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/beagletomb.pro $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/beagletomb.pro.user $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/changelog $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/copyright $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_DIR) /home/skynet/qt_workspace/beagletomb/debian $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_DIR) /home/skynet/qt_workspace/beagletomb/docs $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_DIR) /home/skynet/qt_workspace/beagletomb/images $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_FILE) /home/skynet/qt_workspace/beagletomb/readme.txt $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/
	-$(INSTALL_DIR) /home/skynet/qt_workspace/beagletomb/src $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/


uninstall_other:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/beagletomb.desktop 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/beagletomb.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/beagletomb.pro.user 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/changelog 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/copyright 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/debian 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/docs 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/images 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/readme.txt 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/src
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/extras.ubuntu.com/beagletomb/release/ 


install:  install_target install_sources install_documentation install_other  FORCE

uninstall: uninstall_target uninstall_sources uninstall_documentation uninstall_other   FORCE

FORCE:

